Algoritmo "2"
// Faça um algoritmo que receba um número e mostre uma mensagem caso este
// número segue maior que 80, menor que 25 ou igual a 40.


Var
n1:inteiro
Inicio
  escreva("Digite o numero ")
   leia(n1)

     se (n1 > 80) entao
      escreva ("Maior que 80")
        senao
          se (n1 < 25) entao
           escreva ("Menor que 25")
          senao
        se (n1 = 40) entao
     escreva ("Igual á 40")
   fimse
  fimse
fimse
Fimalgoritmo