Algoritmo "5"
//Escreva um programa que verifique a validade de uma senha
//fornecida pelo usuário. A senha válida é o número 1234.
//Devem ser impressas as seguintes mensagens:
//ACESSO PERMITIDO caso a senha seja válida.
//ACESSO NEGADO caso a senha seja inválida.

Var
senha:inteiro
Inicio
 escreva("Digite sua sen1ha ")
  leia(senha)
   se(senha=1234) entao
    escreva("ACESSO PERMITIDO")
    senao
   escreva("ACESSO NEGADO")
 fimse
Fimalgoritmo