Algoritmo "Números"
// Faça um algoritmo que receba um número e mostre uma mensagem caso
// este número seja maior que 80, menor que 25 ou igual a 40.
Var
n:real
Inicio
  escreva("Digite um numero: ")
   leia(n)
    se (n > 80) entao
     escreva ("Numero alto")
      fimse
     se (n < 25) entao
    escreva ("Numero baixo")
   fimse
  se (n = 40) entao
 escreva ("Numero medio")
fimse
Fimalgoritmo